#!/bin/bash
set -e

. ../aur

install_aur_package google-chrome
install_aur_package visual-studio-code-bin
install_aur_package gpmdp

install_aur_package teamviewer-beta
systemctl enable teamviewerd

install_aur_package keybase-bin

pacman -S --noconfirm go
