#!/bin/bash
. ../common

while IFS='' read -r line || [[ -n "$line" ]]; do
    preference_file="/etc/apt/preferences.d/$line.pref"
    echo -e "Package: $line\nPin: release *\nPin-Priority: -1" > $preference_file
done < "./blacklist-packages"

tasksel install ubuntu-desktop

# The gdm service tries to use Wayland for some reason... so disable it.
sed -i '/WaylandEnable/s/^#//g' /etc/gdm3/custom.conf

# Install fusuma so that we can use gestures to switch apps.
apt-get install -y ruby libinput-tools xdotool
gem install fusuma

# Patch the login screen for styles.
patch /usr/share/gnome-shell/theme/Yaru/gnome-shell.css login-screen-theme.patch

apt-get install gnome-calculator