#!/bin/bash
. ../common

tasksel install ubuntu-desktop

# The gdm service tries to use Wayland for some reason... so disable it.
sed -i '/WaylandEnable/s/^#//g' /etc/gdm3/custom.conf

# Install fusuma so that we can use gestures to switch apps.
apt-get install -y ruby libinput-tools
gem install fusuma