#!/bin/bash
. ../common

apt-get install -y zsh \
    fonts-hack \
    fonts-powerline \
    direnv \
    nano \
    aptitude \
    apt-file \
    htop \
    tree \
    xclip \
    rsync \
    jq \
    git-lfs \
    gnome-keyring \
    command-not-found

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "password\npassword" | passwd
fi

# Add our users
useradd -m -G users,input,sudo -s /bin/zsh pknopf
chfn -f "Paul Knopf" pknopf
groupadd guests
useradd -m -G users,guests -s /bin/bash guest
chfn -f "Guest" guest

# Enable passwordless sudo for pknopf
echo "pknopf ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/pknopf

# Set the user password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd pknopf
else
    echo "Using default user password..."
    echo -en "password\npassword" | passwd pknopf
fi

# Set the guest password
echo -en "guest\nguest" | passwd guest

# Add VS Code
curl -Ls https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | apt-key add -
echo "deb https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
apt-get update
apt-get install -y code

# Add Chrome
curl -Ls https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
apt-get update
apt-get install -y google-chrome-stable

# Add TeamViewer
curl -Ls https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc | apt-key add -
echo "deb http://linux.teamviewer.com/deb stable main" > /etc/apt/sources.list.d/teamviewer-tmp.list
apt-get update
apt-get install -y teamviewer
# We remove the repo now because the teamviewer package reinstalls it
rm /etc/apt/sources.list.d/teamviewer-tmp.list

# Install ripgrep
wget --quiet https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb -O /tmp/ripgrep.deb
gdebi -n /tmp/ripgrep.deb
rm /tmp/ripgrep.deb

# Increase inotify limit
echo "fs.inotify.max_user_watches = 524288" >> /etc/sysctl.conf
# Lower swappiness
echo "vm.swappiness = 10" >> /etc/sysctl.conf