#!/usr/bin/env bash

install_aur_helper() {
    pacman -S --noconfirm git
    git clone https://aur.archlinux.org/trizen.git ~/trizen
    pushd ~/trizen
    makepkg -si --noconfirm
    popd
    rm -r ~/trizen
}

install_aur_package() {
    trizen -S --noconfirm --noedit $1
}