#!/bin/bash
set -e

cd recipes

IMAGES=$(sudo darch recipes build-dep)
TAG=`date +"%Y-%m-%d-%H%M%S"`

sudo darch recipes build \
    -t "$TAG,latest" \
    -p "pauldotknopf/darch-ubuntu-" \
    -e ROOT_PASSWD=$ROOT_PASWD \
    -e USER_PASSWD=$USER_PASSWD \
    $IMAGES