#!/bin/bash
set -e

cd recipes/base
docker build . -t pauldotknopf/darch-ubuntu-base
cd -

cd recipes/base-common
docker build . -t pauldotknopf/darch-ubuntu-base-common
cd -

cd recipes/desktop
docker build . -t pauldotknopf/darch-ubuntu-desktop
cd -

cd recipes/development
docker build . -t pauldotknopf/darch-ubuntu-development
cd -