#!/bin/bash
set -e

. ./build

while read -r IMAGE; do
    sudo darch images push --user $DOCKER_LOGIN_USERNAME:$DOCKER_LOGIN_PASSWORD docker.io/pauldotknopf/darch-arch-personal-$IMAGE:$TAG
    sudo darch images push --user $DOCKER_LOGIN_USERNAME:$DOCKER_LOGIN_PASSWORD docker.io/pauldotknopf/darch-arch-personal-$IMAGE:latest
done <<< "$IMAGES"