#!/usr/bin/env bash

apt-get install -y debhelper \
    pkg-config \
    cmake \
    protobuf-compiler-grpc \
    libprotobuf-dev \
    libgrpc++-dev \
    libdcmtk-dev \
    systemd \
    libsystemd-dev