#!/bin/bash
set -e

. ../common

# Enable audio
install_packages pulseaudio
install_packages pulseaudio-ctl

# I am using Intel graphics on all my machines.
install_packages xf86-video-intel

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages xorg-server xorg-xrandr

# Install i3
install_packages i3 compton xorg-xinit
install_packages j4-dmenu-desktop
install_packages polybar

# Use alacritty as out terminal with tmux
install_packages alacritty-git
install_packages tmux

# Use autorandr to save/load monitor setups
install_packages autorandr-git

# Download the wallpapers.
mkdir -p /usr/share/wallpapers/
curl --output /usr/share/wallpapers/frosted.jpg https://www.pknopf.com/wallpapers/frostedlights.jpg

# Install feh, which we will use to set the wallpaper.
install_packages feh
