#!/bin/bash
set -e

. ../common

# I am using Intel graphics on all my machines.
install_packages xf86-video-intel

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages xorg-server xorg-xrandr

# Install i3
install_packages i3 compton

# Use lxdm to login to i3
install_packages lxdm
install_aur_package lxdm-themes
sudo sed -i "s|theme=.*|theme=Archlinux|" /etc/lxdm/lxdm.conf
sudo sed -i "s|session=.*|session=/usr/bin/i3|" /etc/lxdm/lxdm.conf

# Use alacritty as out terminal.
install_aur_package alacritty-git

# Use autorandr to save/load monitor setups
install_aur_package autorandr-git

# Download the wallpapers.
mkdir -p /usr/share/wallpapers/
curl --output /usr/share/wallpapers/frosted.jpg https://www.pknopf.com/wallpapers/frostedlights.jpg

# Install feh, which we will use to set the wallpaper.
install_aur_package feh

# Enable audio
install_packages pulseaudio