#!/bin/bash
set -e

. ../aur

# I am using Intel graphics on all my machines.
pacman -S xf86-video-intel --noconfirm

# Use X11. Wayland is newer, but options for VNC aren't good.
pacman -S xorg-server xorg-xrandr --noconfirm

# Install i3
pacman -S i3 --noconfirm

# Use SDDM to login to i3
pacman -S sddm --noconfirm
systemctl enable sddm

# Use alacritty as out terminal.
install_aur_package alacritty-git