#!/bin/bash
set -e

. ../aur

# I am using Intel graphics on all my machines.
pacman -S xf86-video-intel --noconfirm

# Use X11. Wayland is newer, but options for VNC aren't good.
pacman -S xorg-server xorg-xrandr --noconfirm

# Install i3
pacman -S i3 --noconfirm

# Use SDDM to login to i3
pacman -S sddm --noconfirm
systemctl enable sddm

# Use alacritty as out terminal.
install_aur_package alacritty-git

# Use autorandr to save/load monitor setups
install_aur_package autorandr-git

# Download the wallpapers.
mkdir -p /usr/share/wallpapers/
curl --output /usr/share/wallpapers/frosted.jpg https://www.pknopf.com/wallpapers/frostedlights.jpg

# Install feh, which we will use to set the wallpaper.
install_aur_package feh