#!/bin/bash
set -e

# I am using Intel graphics on all my machines.
pacman -S xf86-video-intel --noconfirm

# Use X11. Wayland is newer, but options for VNC aren't good.
pacman -S xorg-server --noconfirm

# Install KDE
pacman -S libglvnd phonon-qt5-gstreamer libx264 plasma --noconfirm

# Open login on boot
systemctl enable sddm