#!/bin/bash
set -e
export DEBIAN_FRONTEND=noninteractive

apt-get install -y build-essential \
    git \
    aptitude \
    pbuilder \
    pv \
    cmake \
    python

# Install golang from upstream
curl -Ls https://go.dev/dl/go1.16.13.linux-amd64.tar.gz | sudo tar -C /usr/local -xzf -
sudo ln -s /usr/local/go/bin/go /usr/bin/go

# ./products/qt
# ./products/libimobiledevice
# ./products/abra
# ./products/pv
# ./products/dicom

# Install nodejs
curl -Ls https://nodejs.org/dist/v16.14.0/node-v16.14.0-linux-x64.tar.xz | unxz | tar --strip-components=1 -xpf - -C /usr 

# Setup libsecret for use with git
apt-get install -y libsecret-1-0 libsecret-1-dev libglib2.0-dev
make --directory=/usr/share/doc/git/contrib/credential/libsecret

# Install GitKraken
wget --quiet https://release.gitkraken.com/linux/gitkraken-amd64.deb -O /tmp/gitkraken.deb
gdebi -n /tmp/gitkraken.deb
rm /tmp/gitkraken.deb

# Install Docker
mkdir -p /etc/docker
touch /etc/docker/daemon.json
echo "{\"experimental\": true, \"graph\": \"/var/lib/darch/docker\"}" | tee -a /etc/docker/daemon.json
apt-get install -y docker-ce
systemctl enable docker
usermod -aG docker pknopf
apt-get install -y docker-compose golang-docker-credential-helpers

# Install .NET Core
wget --quiet https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O /tmp/dotnet.deb
gdebi -n /tmp/dotnet.deb
rm /tmp/dotnet.deb
apt-get update
apt-get -y install dotnet-sdk-5.0

# Install ttyd
curl -Ls https://github.com/tsl0922/ttyd/releases/download/1.6.0/ttyd_linux.x86_64 > /usr/bin/ttyd
chmod +x /usr/bin/ttyd

# Install ngrok
wget --quiet https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /tmp/ngrok.zip
unzip -d /usr/bin /tmp/ngrok.zip
rm /tmp/ngrok.zip

# Install ffsend
curl -Ls https://github.com/timvisee/ffsend/releases/download/v0.2.74/ffsend-v0.2.74-linux-x64-static > /usr/bin/ffsend
chmod +x /usr/bin/ffsend

# Install VMWare
wget --quiet https://download3.vmware.com/software/player/file/VMware-Player-Full-16.2.1-18811642.x86_64.bundle -O /tmp/vmware.bundle
chmod +x /tmp/vmware.bundle
echo -ne '\n\n\n' | /tmp/vmware.bundle --console --eulas-agreed
rm /tmp/vmware.bundle

# cmake
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
apt-get update && apt-get install -y cmake