#!/bin/bash
. ../common

apt-get install -y build-essential \
    git \
    golang

./products/qt
./products/libimobiledevice
./products/abra

# Use the gnome-keyring with git
apt-get install -y libgnome-keyring-dev
make --directory=/usr/share/doc/git/contrib/credential/gnome-keyring
git config --global credential.helper /usr/share/doc/git/contrib/credential/gnome-keyring/git-credential-gnome-keyring

# Install GitKraken
apt install -y libgnome-keyring-common libgnome-keyring-dev
wget https://release.gitkraken.com/linux/gitkraken-amd64.deb -O /tmp/gitkraken.deb
gdebi -n /tmp/gitkraken.deb
rm /tmp/gitkraken.deb

# Install KeyBase
wget  https://prerelease.keybase.io/keybase_amd64.deb -O /tmp/keybase.deb
gdebi -n /tmp/keybase.deb
rm /tmp/keybase.deb

# Install Docker
mkdir -p /etc/docker
touch /etc/docker/daemon.json
echo "{\"experimental\": true, \"graph\": \"/var/lib/darch/docker\"}" | tee -a /etc/docker/daemon.json
curl -L https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb https://download.docker.com/linux/ubuntu bionic stable"
# Installing a specific (slightly older) version.
# The reason is because the latest version (5:18.09.0~3-0~ubuntu-bionic)
# has /usr/bin/containerd, which conflicts with Darch.
apt-get install -y docker-ce=18.06.1~ce~3-0~ubuntu
systemctl enable docker
usermod -aG docker pknopf

# Install .NET Core
wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O /tmp/dotnet.deb
gdebi -n /tmp/dotnet.deb
rm /tmp/dotnet.deb
apt-get update
apt-get -y install dotnet-sdk-2.2

# Install gcloud tool
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update && sudo apt-get install -y google-cloud-sdk

# Install gotty
curl -L https://github.com/yudai/gotty/releases/download/v2.0.0-alpha.3/gotty_2.0.0-alpha.3_linux_amd64.tar.gz | tar zxf - -C /usr/bin

# Install ngrok
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /tmp/ngrok.zip
unzip -d /usr/bin /tmp/ngrok.zip
rm /tmp/ngrok.zip

# Install ffsend
curl -L https://github.com/timvisee/ffsend/releases/download/v0.2.34/ffsend-v0.2.34-linux-x64 > /usr/bin/ffsend
chmod +x /usr/bin/ffsend

# lldb
apt-get install -y lldb-7
ln -s /usr/bin/lldb-7 /usr/bin/lldb

# boostnote
curl -L https://github.com/BoostIO/boost-releases/releases/download/v0.11.15/boostnote_0.11.15_amd64.deb > /tmp/boostnote.deb
gdebi -n /tmp/boostnote.deb
rm /tmp/boostnote.deb