#!/bin/bash
set -e
export DEBIAN_FRONTEND=noninteractive

apt-get install -y build-essential \
    git \
    golang \
    aptitude \
    pbuilder

./products/qt
./products/libimobiledevice
./products/abra

# Install nodejs
curl -Ls https://nodejs.org/dist/v10.15.3/node-v10.15.3-linux-x64.tar.xz | unxz | tar --strip-components=1 -xpf - -C /usr 

# Setup libsecret for use with git
apt-get install -y libsecret-1-0 libsecret-1-dev libglib2.0-dev
make --directory=/usr/share/doc/git/contrib/credential/libsecret

# Install GitKraken
wget --quiet https://release.gitkraken.com/linux/gitkraken-amd64.deb -O /tmp/gitkraken.deb
gdebi -n /tmp/gitkraken.deb
rm /tmp/gitkraken.deb

# Install Docker
mkdir -p /etc/docker
touch /etc/docker/daemon.json
echo "{\"experimental\": true, \"graph\": \"/var/lib/darch/docker\"}" | tee -a /etc/docker/daemon.json
apt-get install -y docker-ce
systemctl enable docker
usermod -aG docker pknopf
apt-get install -y docker-compose golang-docker-credential-helpers

# Install .NET Core
wget --quiet https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O /tmp/dotnet.deb
gdebi -n /tmp/dotnet.deb
rm /tmp/dotnet.deb
apt-get update
apt-get -y install dotnet-sdk-3.1

# Install ttyd
curl -Ls https://github.com/tsl0922/ttyd/releases/download/1.6.0/ttyd_linux.x86_64 > /usr/bin/ttyd
chmod +x /usr/bin/ttyd

# Install ngrok
wget --quiet https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O /tmp/ngrok.zip
unzip -d /usr/bin /tmp/ngrok.zip
rm /tmp/ngrok.zip

# Install ffsend
curl -Ls https://github.com/timvisee/ffsend/releases/download/v0.2.46/ffsend-v0.2.46-linux-x64-static > /usr/bin/ffsend
chmod +x /usr/bin/ffsend

# Install VMWare
wget --quiet https://download3.vmware.com/software/player/file/VMware-Player-15.5.6-16341506.x86_64.bundle -O /tmp/vmware.bundle
chmod +x /tmp/vmware.bundle
echo -ne '\n\n\n' | /tmp/vmware.bundle --console --eulas-agreed
rm /tmp/vmware.bundle

# Install delta (for diffs)
# curl -Ls https://github.com/dandavison/delta/releases/download/0.1.1/git-delta_0.1.1_amd64.deb > /tmp/delta.deb
# gdebi -n /tmp/delta.deb
# rm /tmp/delta.deb

# lldb
#apt-get install -y lldb-7
#ln -s /usr/bin/lldb-7 /usr/bin/lldb

# boostnote
# Note working on Ubuntu 20
#curl -Ls https://github.com/BoostIO/boost-releases/releases/download/v0.12.1/boostnote_0.12.1_amd64.deb > /tmp/boostnote.deb
#gdebi -n /tmp/boostnote.deb
#rm /tmp/boostnote.deb

# cmake
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
apt-get install -y cmake