#!/bin/bash
. ../common

# Add the official Ubuntu repositories.
echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic multiverse universe main restricted" >> /etc/apt/sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates multiverse universe main restricted" >> /etc/apt/sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://security.ubuntu.com/ubuntu bionic-security restricted main universe multiverse" >> /etc/apt/sources.list
echo "deb http://archive.neon.kde.org/user bionic main" >> /etc/apt/sources.list

apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E6D4736255751E5D
# Install packages from neon first.
echo -e "Package: *\nPin: origin archive.neon.kde.org\nPin-Priority: 900" > /etc/apt/preferences

apt-get update
apt-get upgrade  -y

# Install Darch.
apt-get install -y darch
systemctl enable containerd
# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
echo "root = \"/var/lib/darch/containerd\"" >> /etc/containerd/config.toml
# Darch installs grub-common, which installs "grub-initrd-fallback.service".
# This fails on boot. Let's just disable it.
systemctl disable grub-initrd-fallback

# Enable default DHCP networking.
apt-get install -y network-manager
mkdir -p /etc/netplan
cp network.yaml /etc/netplan

# Setup the locales.
locale-gen --purge en_US.UTF-8
echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale

# Set the timezone to EST
rm /etc/localtime
ln -s ../usr/share/zoneinfo/America/New_York /etc/localtime

# We need this in a few places.
apt-get install -y tasksel gdebi-core

# Enable ssh access
apt-get install -y openssh-server

# Add nvidia drivers (for my XPS 5970)
apt-get install -y nvidia-driver-390
# When running in Travis, the nvidia package will create an initrd for
# the kernel version of the build host. I'm not sure why this is, but
# it affects extracting the image for boot (later on), so delete it.
rm -f /boot/initrd.img-4.4.0-101-generic