#!/bin/bash
. ../common

# Add the official Ubuntu repositories.
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic main restricted"
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic-updates main restricted"
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic universe"
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic-updates universe"
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic multiverse"
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic-updates multiverse"
add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ cosmic-backports main restricted universe multiverse"
add-apt-repository "deb http://security.ubuntu.com/ubuntu cosmic-security main restricted"
add-apt-repository "deb http://security.ubuntu.com/ubuntu cosmic-security universe"
add-apt-repository "deb http://security.ubuntu.com/ubuntu cosmic-security multiverse"
apt-get update

# Install Darch.
apt-get install -y darch
systemctl enable containerd
# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
mkdir -p /etc/containerd
echo "root = \"/var/lib/darch/containerd\"" > /etc/containerd/config.toml
# Darch installs grub-common, which installs "grub-initrd-fallback.service".
# This fails on boot. Let's just disable it.
systemctl disable grub-initrd-fallback

# Enable default DHCP networking.
apt-get install -y network-manager
mkdir -p /etc/netplan
cp network.yaml /etc/netplan

# Setup the locales.
locale-gen --purge en_US.UTF-8
echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale

# Set the timezone to EST
rm /etc/localtime
ln -s ../usr/share/zoneinfo/America/New_York /etc/localtime

# We need this in a few places.
apt-get install -y tasksel gdebi-core

# Enable ssh access
apt-get install -y openssh-server

# Add nvidia drivers (for my XPS 5970)
echo "current init images"
find /boot -name "initrd*generic"
apt-get install -y nvidia-driver-390
echo "new init images"
find /boot -name "initrd*generic"
exit 1