#!/bin/bash
. ../common

# Add the official Ubuntu repositories.
echo "deb http://us.archive.ubuntu.com/ubuntu/ disco multiverse universe main restricted" >> /etc/apt/sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ disco-updates multiverse universe main restricted" >> /etc/apt/sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ disco-backports main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://security.ubuntu.com/ubuntu disco-security restricted main universe multiverse" >> /etc/apt/sources.list

apt-get update
# The "linux-image-generic" gets held back for some reason.
# The "--with-new-pkgs" forces the package to be upgraded.
apt-mark hold linux-image-generic
apt-get --with-new-pkgs upgrade -y

# Remove all vmlinux/initrd from the boot.
# There may be many versions.
rm -r /boot/*
# Now reinstall the files to /boot.
apt-cache depends linux-image-generic | sed -n 2p | tr -s ' ' | cut -d ' ' -f 3 | xargs apt-get --reinstall install -y

# Install Darch.
apt-get install -y darch
systemctl enable containerd
# I store containerd on /var/lib/darch/containerd, because /var/lib/darch
# is an external partition. This way, images are persisted across boots.
echo "root = \"/var/lib/darch/containerd\"" >> /etc/containerd/config.toml
# Darch installs grub-common, which installs "grub-initrd-fallback.service".
# This fails on boot. Let's just disable it.
systemctl disable grub-initrd-fallback

# Enable default DHCP networking.
apt-get install -y network-manager
mkdir -p /etc/netplan
cp network.yaml /etc/netplan

# Setup the locales.
locale-gen --purge en_US.UTF-8
echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale

# Set the timezone to EST
rm /etc/localtime
ln -s ../usr/share/zoneinfo/America/New_York /etc/localtime

# We need this in a few places.
apt-get install -y tasksel gdebi-core

# Enable ssh access
apt-get install -y openssh-server

# Add nvidia drivers (for my XPS 5970)
add-apt-repository -y ppa:graphics-drivers/ppa
apt-get install -y nvidia-driver-418 nvidia-modprobe
# When running in Travis, the nvidia package will create an initrd for
# the kernel version of the build host. I'm not sure why this is, but
# it affects extracting the image for boot (later on), so delete it.
rm -f /boot/initrd.img-4.4.0-101-generic

# Use the intel driver on boot by default. The nvidia driver has issues with system resuming.
# The prime-select command fails if "/etc/default/grub" doesn't exist.
touch /etc/default/grub
prime-select intel

# Increase the size of the linux console text.
sed -i 's/FONTSIZE=.*/FONTSIZE="16x32"/g' /etc/default/console-setup