#!/bin/bash
. ../common

apt-get install -y zsh \
    fonts-hack \
    zsh-theme-powerlevel9k \
    direnv \
    nano \
    aptitude \
    apt-file \
    htop \
    tree

# Set the root password
if [ -n  "$ROOT_PASSWD" ]; then
    echo "Using root password provided by environment variable..."
    echo -en "$ROOT_PASSWD\n$ROOT_PASSWD" | passwd
else
    echo "Using default root password..."
    echo -en "password\npassword" | passwd
fi

# Add our users
useradd -m -G users,sudo -s /bin/zsh pknopf
groupadd guests
useradd -m -G users,guests -s /bin/bash guest

# Set the user password
if [ -n  "$USER_PASSWD" ]; then
    echo "Using user password provided by environment variable..."
    echo -en "$USER_PASSWD\n$USER_PASSWD" | passwd pknopf
else
    echo "Using default user password..."
    echo -en "password\npassword" | passwd pknopf
fi

# Set the guest password
echo -en "guest\nguest" | passwd guest

# Add VS Code
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | apt-key add -
echo "deb https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
apt-get update
apt-get install -y code

# Add Chrome
curl -L https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
apt-get update
apt-get install -y google-chrome-stable

# Add TeamViewer
curl -L https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc | apt-key add -
echo "deb http://linux.teamviewer.com/deb stable main" > /etc/apt/sources.list.d/teamviewer-tmp.list
apt-get update
apt-get install -y teamviewer
# We remove the repo now because the teamviewer package reinstalls it
rm /etc/apt/sources.list.d/teamviewer-tmp.list

# Install ripgrep
wget https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb -O /tmp/ripgrep.deb
gdebi -n /tmp/ripgrep.deb
rm /tmp/ripgrep.deb