#!/bin/bash
set -e

. ../common

# I am using Intel graphics on all my machines.
install_packages xf86-video-intel

# Use X11. Wayland is newer, but options for VNC aren't good.
install_packages xorg-server

# Install KDE
install_packages libglvnd phonon-qt5-gstreamer libx264 plasma

# Use their terminal.
install_packages konsole

# Open login on boot
systemctl enable sddm
